# ===============================
# Aplicacion
# ===============================
spring.application.name=Inventario
server.port=8080
server.forward-headers-strategy=FRAMEWORK

# ===============================
# DataSource (PostgreSQL)
# ===============================
spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DB_USER_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}
spring.datasource.driver-class-name=org.postgresql.Driver

#poll
#spring.datasource.hikari.maximum-pool-size=5

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
app.jwt.secret=Y2FtYmlhLWVzdGEtY2xhdmUtcG9yLXVuYS1tYXMtbGFyZ2EtZW4tcHJvZHVjY2lvbg==
app.jwt.expiration-ms=600000
app.jwt.refresh-expiration-ms=604800000
app.jwt.issuer=papeleria-inventario

# Cookie security settings (false in dev/local, true in prod HTTPS)
app.security.cookie.secure=${LOCAL_MODE}

# CORS Trusted Origins configuration (comma-separated list of allowed origins)
app.security.cors.allowed-origins=${URL_CORS}

# ===============================
# Swagger / OpenAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=INFO
logging.level.com.guerrero.Inventario=DEBUG
