# ===============================
# Aplicacion
# ===============================
spring.application.name=Inventario
server.port=8080

# ===============================
# DataSource (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/papeleria
spring.datasource.username=postgres
spring.datasource.password=secret123
#spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:6543/postgres
#spring.datasource.username=postgres.tazenafawgxnnmoavmum
#spring.datasource.password=wB1cIVo6lrGbIDSd
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
app.jwt.secret=Y2FtYmlhLWVzdGEtY2xhdmUtcG9yLXVuYS1tYXMtbGFyZ2EtZW4tcHJvZHVjY2lvbg==
app.jwt.expiration-ms=86400000
app.jwt.issuer=papeleria-inventario

# ===============================
# Swagger / OpenAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=INFO
logging.level.com.guerrero.Inventario=DEBUG
